
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;

import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPClient;
import org.apache.commons.net.ftp.FTPFile;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ade
 */
public class upfles extends javax.swing.JFrame {

    String hostname = "iska.id1945.com",
            username = "u794902763",
            pass = "de3fr4gt5",
            prefixFolder = "E:/proyeKerja/onlineshop/src/upload/";

    /**
     * Creates new form upfles
     */
    public upfles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Pilih file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButton1)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-338)/2, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

    private String UploadHere(File flUpp, String direkToryn) {
        String getBack = "";
        FTPClient ftp = new FTPClient();
        try {
            ftp.connect(hostname);
            ftp.login(username, pass);
            ftp.setFileType(FTP.BINARY_FILE_TYPE);
            ftp.setFileTransferMode(FTP.BINARY_FILE_TYPE);
            ftp.enterLocalPassiveMode();
            FileInputStream fis = new FileInputStream(flUpp);
            if (direkToryn.length() > 0) {
                StringTokenizer stk = new StringTokenizer(direkToryn, "/");
                String direktoryNow = "";
                while (stk.hasMoreTokens()) {
                    direktoryNow = stk.nextToken();
                    System.out.println("in directory " + direktoryNow);
                    ftp.changeWorkingDirectory(direktoryNow);
                }
            }
            ftp.storeFile(flUpp.getName(), fis);
            ftp.logout();
        } catch (Exception ex) {
            getBack = ex.getMessage();
        }
        return getBack;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc = new JFileChooser();

        if (fc.showOpenDialog(this) == fc.APPROVE_OPTION) {
            File fl = fc.getSelectedFile();
            try {
                FileInputStream fstream = new FileInputStream(fl);
                DataInputStream in = new DataInputStream(fstream);
                BufferedReader br = new BufferedReader(new InputStreamReader(in));
                String strLine;
                File flUpp = fc.getSelectedFile();
                String getBir = "";



                while ((strLine = br.readLine()) != null && getBir.length() < 1) {
                    if (strLine.length() > 0) {
                        flUpp = new File(strLine);
                        if (flUpp.isFile()) {
                            System.out.println("prefixFolder" + prefixFolder + " get filename " + flUpp);
                            strLine = strLine.substring(prefixFolder.length());
                            try {
                                strLine = strLine.substring(0, strLine.length() - flUpp.getName().length() - 1);
                                strLine = strLine.replace("\\", "/");
                            } catch (Exception ex) {
                                strLine = "";
                            }
                            System.out.println("folder = " + strLine);
                            getBir = UploadHere(flUpp, strLine);
                        }
                    }
                }

                if (getBir.length() < 1) {
                    javax.swing.JOptionPane.showConfirmDialog(null, "Sudah di upload", "Information",
                            javax.swing.JOptionPane.PLAIN_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showConfirmDialog(null, "Error " + getBir, "Error",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                }

                in.close();
            } catch (Exception ex) {
                javax.swing.JOptionPane.showConfirmDialog(null, "Error " + ex.getMessage(), "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(upfles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(upfles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(upfles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(upfles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new upfles().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
