
import java.awt.Rectangle;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;

import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPClient;
import org.apache.commons.net.ftp.FTPFile;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ade
 */
public class upfles extends javax.swing.JFrame {

    String hostname = "",
            username = "",
            pass = "",
            prefixFolder = "";

    /**
     * Creates new form upfles
     */
    public upfles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        hostFtp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        USerFTP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prefixFile = new javax.swing.JTextField();
        PAssFTp = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Pilih file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Hostname ftp");

        jLabel2.setText("Username ftp");

        jLabel3.setText("password ftp");

        jLabel4.setText("prefix folder");

        jToggleButton1.setText("Ambil setting");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jProgressBar1.setBackground(new java.awt.Color(255, 153, 153));
        jProgressBar1.setForeground(new java.awt.Color(102, 102, 102));
        jProgressBar1.setMaximum(20);
        jProgressBar1.setName("jProgressBar1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hostFtp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prefixFile))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PAssFTp))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(USerFTP, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostFtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USerFTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PAssFTp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefixFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton1))
                .addGap(39, 39, 39))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private String UploadHere(File flUpp, String direkToryn) {
        String getBack = "";
        FTPClient ftp = new FTPClient();
        try {
            ftp.connect(hostname);
            ftp.login(username, pass);
            ftp.setFileType(FTP.BINARY_FILE_TYPE);
            ftp.setFileTransferMode(FTP.BINARY_FILE_TYPE);
            ftp.enterLocalPassiveMode();
            FileInputStream fis = new FileInputStream(flUpp);
            if (direkToryn.length() > 0) {
                StringTokenizer stk = new StringTokenizer(direkToryn, "/");
                String direktoryNow = "";
                while (stk.hasMoreTokens()) {
                    direktoryNow = stk.nextToken();
                    ftp.changeWorkingDirectory(direktoryNow);
                }
            }
            ftp.storeFile(flUpp.getName(), fis);
            System.out.println("upload success");
            ftp.logout();
        } catch (Exception ex) {
            getBack = ex.getMessage();
        }
        return getBack;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc = new JFileChooser();
        hostname = hostFtp.getText();
        username = USerFTP.getText();
        pass = PAssFTp.getText();
        prefixFolder = prefixFile.getText();
        prefixFolder = prefixFolder.replace("\\", "/");
        if (hostname.length() > 0 && username.length() > 0 && pass.length() > 0 && prefixFolder.length() > 0) {
            if (fc.showOpenDialog(this) == fc.APPROVE_OPTION) {
                File fl = fc.getSelectedFile();
                try {
                    FileInputStream fstream = new FileInputStream(fl);
                    DataInputStream in = new DataInputStream(fstream);
                    BufferedReader br = new BufferedReader(new InputStreamReader(in));
                    String strLine = "";
                    File flUpp = fc.getSelectedFile();
                    String getBir = "";


                    jProgressBar1.setMinimum(1);
                    int i = 0;
                    while ((strLine = br.readLine()) != null) {
                        i++;
                    }
                    jProgressBar1.setMaximum(i);
                    fstream.close();
                    in.close();
                    br.close();

                    fstream = new FileInputStream(fl);
                    in = new DataInputStream(fstream);
                    br = new BufferedReader(new InputStreamReader(in));

                    
                    jProgressBar1.setValue(0);
                    Rectangle progressRect = jProgressBar1.getBounds();
                    progressRect.x = 0;
                    progressRect.y = 0;
                    jProgressBar1.paintImmediately(progressRect);
                    i=0;
                    while ((strLine = br.readLine()) != null && getBir.length() < 1) {
                        jProgressBar1.setValue(i);
                        jProgressBar1.paintImmediately(progressRect);
                        if (strLine.length() > 0) {
                            flUpp = new File(prefixFolder + "/" + strLine);
                            if (flUpp.isFile()) {
                                try {
                                    strLine = strLine.substring(0, strLine.length() - flUpp.getName().length() - 1);
                                    strLine = strLine.replace("\\", "/");
                                } catch (Exception ex) {
                                    strLine = "";
                                }
                                System.out.println("up this = " + strLine + " - filename = " + flUpp.getName());
                                getBir = UploadHere(flUpp, strLine);
                            }
                        }
                        i++;
                    }
                    jProgressBar1.setValue(i);
                    jProgressBar1.paintImmediately(progressRect);
                    fstream.close();
                    in.close();
                    br.close();

                    if (getBir.length() < 1) {
                        javax.swing.JOptionPane.showConfirmDialog(null, "Sudah di upload", "Information",
                                javax.swing.JOptionPane.PLAIN_MESSAGE);
                    } else {
                        javax.swing.JOptionPane.showConfirmDialog(null, "Error " + getBir, "Error",
                                javax.swing.JOptionPane.ERROR_MESSAGE);
                    }

                    in.close();
                } catch (Exception ex) {
                    javax.swing.JOptionPane.showConfirmDialog(null, "Error " + ex.getMessage(), "Error",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showConfirmDialog(null, "Isi semua", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        JFileChooser fc = new JFileChooser();
        if (fc.showOpenDialog(this) == fc.APPROVE_OPTION) {
            File fl = fc.getSelectedFile();
            try {
                FileInputStream fstream = new FileInputStream(fl);
                DataInputStream in = new DataInputStream(fstream);
                BufferedReader br = new BufferedReader(new InputStreamReader(in));
                String strLine;
                while ((strLine = br.readLine()) != null) {
                    if (strLine.length() > 0) {
                        StringTokenizer stk = new StringTokenizer(strLine, ";");
                        hostFtp.setText(stk.nextToken());
                        USerFTP.setText(stk.nextToken());
                        PAssFTp.setText(stk.nextToken());
                        prefixFile.setText(stk.nextToken());
                    }
                }
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(upfles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(upfles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(upfles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(upfles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new upfles().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PAssFTp;
    private javax.swing.JTextField USerFTP;
    private javax.swing.JTextField hostFtp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField prefixFile;
    // End of variables declaration//GEN-END:variables
}
